"""
strategy_framework/config/constituents.py
=========================================
Symbol-keyed NIFTY-50 index weights and sector map.

SINGLE SOURCE OF TRUTH: everything below is loaded from the ONE editable master,
`nifty-50-stock-list.csv` (columns: Symbol, Company Name, Sector, Weight). The
symbol list, sectors AND weights all come from that file — there is no longer a
hand-maintained weight dict here to drift out of sync. To change the universe or a
weight, edit the CSV; `breeze_symbol_map.json` is regenerated by
generate_breeze_mappings.py, and validate_constituents_alignment.py / the
data_agent registry cross-check it.

Public API is unchanged (WEIGHTS_PCT, HEAVYWEIGHTS, SECTOR_OF, weight_of,
sector_of, sectors, symbols, load_weights) so the 6+ signal modules that import
this keep working exactly as before.
"""
from __future__ import annotations
import csv
import json
import os

_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
_CSV = os.path.join(_ROOT, "nifty-50-stock-list.csv")


def _load_master() -> tuple[dict[str, float], dict[str, str]]:
    """Read weights + sectors from the CSV master. Weight column optional per-row
    (a symbol with no weight simply won't appear in WEIGHTS_PCT)."""
    weights: dict[str, float] = {}
    sectors_of: dict[str, str] = {}
    if os.path.exists(_CSV):
        with open(_CSV, newline="") as f:
            for row in csv.DictReader(f):
                sym = (row.get("Symbol") or "").strip()
                if not sym:
                    continue
                sectors_of[sym] = (row.get("Sector") or "").strip()
                w = row.get("Weight")
                if w not in (None, ""):
                    try:
                        weights[sym] = float(w)
                    except (TypeError, ValueError):
                        pass
    return weights, sectors_of


# Free-float weights (%) and sectors — both from the CSV master.
WEIGHTS_PCT, SECTOR_OF = _load_master()

HEAVYWEIGHTS = [s for s, w in sorted(WEIGHTS_PCT.items(), key=lambda x: -x[1])[:10]]


def weight_of(symbol: str) -> float:
    return WEIGHTS_PCT.get(symbol, 0.0)


def sector_of(symbol: str) -> str:
    return SECTOR_OF.get(symbol, "Unknown")


def sectors() -> list[str]:
    return sorted(set(SECTOR_OF.values()))


def symbols() -> list[str]:
    """All constituent tickers we know a weight or sector for."""
    return sorted(set(WEIGHTS_PCT) | set(SECTOR_OF))


def load_weights(path: str) -> dict[str, float]:
    """Optional runtime override from a JSON {symbol: weight} (e.g. a live refresh)."""
    if path and os.path.exists(path):
        with open(path) as f:
            WEIGHTS_PCT.update(json.load(f))
    return WEIGHTS_PCT
