-- ============================================================================
-- Upstox Company Fundamentals — PostgreSQL schema
-- ============================================================================
-- Aligns with POSTGRES_MIGRATION_PLAN.md:
--   * a NEW logical schema `fundamentals` in the single NiftyOptions PG DB
--     (sits next to market/, analytics/, strategy/, system/, news/).
--   * plain tables — fundamentals are low-frequency (quarterly/annual), so NO
--     TimescaleDB hypertables (those are for market.chain_rows / price_bars).
--   * BIGINT GENERATED BY DEFAULT AS IDENTITY keys (repo convention).
--   * named UNIQUE constraints so the loader can ON CONFLICT ... DO UPDATE.
--   * you can paste this into an Alembic revision's upgrade() (op.execute) or
--     apply it directly; everything is IF NOT EXISTS / idempotent.
--
-- Design: Upstox returns TIDY data (a metric + a `history` array of
-- {period,value,change}). So we store LONG, keyed by (isin, ..., period) —
-- new line items become rows, not columns. ISIN is the join key throughout;
-- `companies` bridges ISIN <-> registry symbol (keeps the constituents master
-- single-source per DATA_SOURCES.md). Money is in CRORE unless `units` says else.
-- ============================================================================

CREATE SCHEMA IF NOT EXISTS fundamentals;
SET search_path TO fundamentals, public;

-- ---------------------------------------------------------------------------
-- Dimension: one row per company. Bridge ISIN <-> registry symbol.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS fundamentals.companies (
    isin            TEXT PRIMARY KEY,              -- e.g. INE002A01018
    symbol          TEXT,                          -- NSE trading symbol, e.g. RELIANCE
    instrument_key  TEXT,                          -- e.g. NSE_EQ|INE002A01018
    company_name    TEXT,
    updated_at      TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS ix_companies_symbol ON fundamentals.companies(symbol);

-- ---------------------------------------------------------------------------
-- /profile — latest snapshot (1 row per isin, overwritten on refresh)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS fundamentals.company_profile (
    isin                 TEXT PRIMARY KEY REFERENCES fundamentals.companies(isin),
    description          TEXT,                     -- data.company_profile
    sector               TEXT,                     -- Upstox classification (NOT sector_tree taxonomy)
    sector_mcap_inr_cr   NUMERIC,                  -- sector_market_cap_inr.value (crore)
    sector_mcap_usd      NUMERIC,                  -- sector_market_cap_usd.value
    sector_mcap_usd_unit TEXT,                     -- 'billion' | 'million'
    fetched_at           TIMESTAMPTZ
);

-- ---------------------------------------------------------------------------
-- income / balance / cash-flow — ONE long table for all three statements.
-- section='summary' -> headline categories; section='full' -> fs=true items.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS fundamentals.financials (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    isin          TEXT NOT NULL REFERENCES fundamentals.companies(isin),
    statement     TEXT NOT NULL CHECK (statement IN ('income','balance','cashflow')),
    basis         TEXT NOT NULL CHECK (basis IN ('consolidated','standalone')),
    time_period   TEXT NOT NULL CHECK (time_period IN ('yearly','quarterly')),
    section       TEXT NOT NULL CHECK (section IN ('summary','full')),
    line_item     TEXT NOT NULL,                  -- 'revenue' | 'Total Assets' | 'EPS - Basic' | ...
    period_label  TEXT NOT NULL,                  -- raw API label, e.g. 'Mar 2026'
    period_end    DATE,                           -- normalized, e.g. 2026-03-31
    value         NUMERIC,                        -- crore (or EPS in rupees)
    change_pct    NUMERIC,                        -- summary rows only; NULL otherwise
    units         TEXT DEFAULT 'crore',
    fetched_at    TIMESTAMPTZ,
    CONSTRAINT uq_financials
        UNIQUE (isin, statement, basis, time_period, section, line_item, period_label)
);
CREATE INDEX IF NOT EXISTS ix_fin_lookup
    ON fundamentals.financials(isin, statement, time_period, period_end);

-- ---------------------------------------------------------------------------
-- /key-ratios — snapshot (no period from API). as_of = pull date, so repeated
-- pulls accrete a time series of P/E, ROE, etc.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS fundamentals.key_ratios (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    isin          TEXT NOT NULL REFERENCES fundamentals.companies(isin),
    ratio         TEXT NOT NULL,                  -- 'P/E'|'P/B'|'ROA'|'ROE'|'ROCE'|'EV/EBITDA'
    company_value NUMERIC,
    sector_value  NUMERIC,
    as_of         DATE NOT NULL,
    fetched_at    TIMESTAMPTZ,
    CONSTRAINT uq_key_ratios UNIQUE (isin, ratio, as_of)
);
CREATE INDEX IF NOT EXISTS ix_ratios_isin ON fundamentals.key_ratios(isin, ratio, as_of);

-- ---------------------------------------------------------------------------
-- /share-holdings — quarterly percentage per category.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS fundamentals.shareholding (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    isin          TEXT NOT NULL REFERENCES fundamentals.companies(isin),
    category      TEXT NOT NULL,                  -- promoters|fii|other_dii|mutual_funds|retail_and_other
    period_label  TEXT NOT NULL,                  -- 'Mar 2026'
    period_end    DATE,
    pct           NUMERIC,                        -- % of total shares
    fetched_at    TIMESTAMPTZ,
    CONSTRAINT uq_shareholding UNIQUE (isin, category, period_label)
);
CREATE INDEX IF NOT EXISTS ix_shp_isin ON fundamentals.shareholding(isin, period_end);

-- ---------------------------------------------------------------------------
-- /corporate-actions — dividends/bonus/splits/rights. action_uid computed by
-- loader (type|ex_date|amount|ratio) so nullable fields don't break UNIQUE.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS fundamentals.corporate_actions (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    isin          TEXT NOT NULL REFERENCES fundamentals.companies(isin),
    action_type   TEXT NOT NULL,                  -- 'Dividend'|'Bonus'|'Split'|'Rights'
    ex_date       DATE,                           -- parsed from expiry_date
    ex_date_raw   TEXT,                           -- original string (kept if unparseable)
    amount        NUMERIC,                        -- dividends; NULL otherwise
    ratio         TEXT,                           -- bonus/split ratio '1:1'; NULL otherwise
    details       JSONB,                          -- event_details[]
    action_uid    TEXT NOT NULL,
    fetched_at    TIMESTAMPTZ,
    CONSTRAINT uq_corp_actions UNIQUE (isin, action_uid)
);
CREATE INDEX IF NOT EXISTS ix_ca_isin_date ON fundamentals.corporate_actions(isin, ex_date);

-- ---------------------------------------------------------------------------
-- /competitors — peer edges (subject isin -> peer).
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS fundamentals.competitors (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    isin                TEXT NOT NULL REFERENCES fundamentals.companies(isin),
    peer_instrument_key TEXT NOT NULL,            -- 'NSE_EQ|INE...'
    peer_isin           TEXT,
    peer_description    TEXT,
    peer_sector         TEXT,
    peer_mcap_inr_cr    NUMERIC,
    peer_mcap_usd       NUMERIC,
    peer_mcap_usd_unit  TEXT,
    fetched_at          TIMESTAMPTZ,
    CONSTRAINT uq_competitors UNIQUE (isin, peer_instrument_key)
);
CREATE INDEX IF NOT EXISTS ix_comp_isin ON fundamentals.competitors(isin);

-- ---------------------------------------------------------------------------
-- Run log — one row per (isin, endpoint) fetch, for freshness/debugging.
-- (Mirrors the plan's system.job_runs idea, scoped to fundamentals.)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS fundamentals.fetch_log (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    isin        TEXT,
    endpoint    TEXT,
    http_status INTEGER,
    ok          BOOLEAN,
    message     TEXT,
    fetched_at  TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS ix_flog_time ON fundamentals.fetch_log(fetched_at);

-- ---------------------------------------------------------------------------
-- /asset_quality — scraped from Screener.in for banks
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS fundamentals.asset_quality (
    symbol TEXT NOT NULL,
    period_end DATE NOT NULL,
    gnpa_pct NUMERIC,
    nnpa_pct NUMERIC,
    pcr_pct NUMERIC,
    nim_pct NUMERIC,
    fetched_at TIMESTAMPTZ,
    PRIMARY KEY (symbol, period_end)
);
